### ISSUE TITLE
Streamline common attributes across profile types

### ISSUE THREAD

**Issue by dkarlovi** [sigwinhq/ariadne#38]
For example,

```yaml
apply:
    attribute:
        description: foo
```

can be

```yaml
apply:
    description: foo
```

since both client support it.
