### ISSUE TITLE
Dynamic attributes support

### ISSUE THREAD

**Issue by dkarlovi** [sigwinhq/ariadne#39]
For example:

```yaml
apply:
    attribute:
        description: '"See more at " ~ pages_url(repository)'
```
